import os
import io
import zipfile
import json
import xml.etree.ElementTree as ET

def export_kml(simulation_data):
    """
    Generates Google Earth KML string representation of the inundation timesteps.
    """
    dam_name = simulation_data.get("dam_name", "Dam")
    timesteps = simulation_data.get("geojson_timesteps", [])
    
    kml_header = f"""<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>BreachSense Inundation Model - {dam_name}</name>
    <description>Dam Break Flood Extent Timesteps generated by BreachSense Hydrodynamic Engine</description>
    
    <!-- Style definitions for depth polygons -->
    <Style id="shallowFlood">
      <PolyStyle><color>7fFA2600</color><fill>1</fill><outline>1</outline></PolyStyle>
      <LineStyle><color>ffFA2600</color><width>2</width></LineStyle>
    </Style>
    <Style id="deepFlood">
      <PolyStyle><color>7f2626DC</color><fill>1</fill><outline>1</outline></PolyStyle>
      <LineStyle><color>ff2626DC</color><width>2</width></LineStyle>
    </Style>
"""
    
    kml_body = ""
    for step in timesteps:
        t_min = step.get("timestep_min", 0)
        max_depth = step.get("max_depth_m", 0)
        geojson = step.get("geojson", {})
        features = geojson.get("features", [])
        
        kml_body += f"""
    <Folder>
      <name>Time +{t_min} Mins (Reach: {step.get('reach_dist_km', 0)} km)</name>
"""
        for feat in features:
            coords = feat.get("geometry", {}).get("coordinates", [[]])[0]
            coord_str = " ".join([f"{c[0]},{c[1]},0" for c in coords])
            style_id = "deepFlood" if max_depth > 5.0 else "shallowFlood"
            
            kml_body += f"""
      <Placemark>
        <name>Inundation Zone t={t_min}m</name>
        <description>Max Depth: {max_depth}m, Flooded Area: {step.get('flooded_area_sqkm', 0)} sqkm</description>
        <styleUrl>#{style_id}</styleUrl>
        <Polygon>
          <outerBoundaryIs>
            <LinearRing>
              <coordinates>{coord_str}</coordinates>
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
      </Placemark>
"""
        kml_body += "    </Folder>\n"
        
    kml_footer = """  </Document>
</kml>"""
    
    return kml_header + kml_body + kml_footer


def export_shapefile_zip(simulation_data):
    """
    Generates a zipped ESRI Shapefile archive containing .shp, .shx, .dbf, .prj and .geojson.
    """
    dam_name = simulation_data.get("dam_name", "Dam").replace(" ", "_")
    timesteps = simulation_data.get("geojson_timesteps", [])
    
    # Consolidate all timesteps into single master GeoJSON FeatureCollection
    all_features = []
    for step in timesteps:
        t_min = step.get("timestep_min", 0)
        geojson = step.get("geojson", {})
        for feat in geojson.get("features", []):
            feat_copy = dict(feat)
            feat_copy["properties"]["timestep_min"] = t_min
            all_features.append(feat_copy)
            
    master_geojson = {
        "type": "FeatureCollection",
        "features": all_features
    }
    
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # GeoJSON file
        geojson_str = json.dumps(master_geojson, indent=2)
        zf.writestr(f"{dam_name}_flood_extent.geojson", geojson_str.encode("utf-8"))
        
        # WGS84 PRJ spatial reference file
        prj_content = 'GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]'
        zf.writestr(f"{dam_name}_flood_extent.prj", prj_content.encode("utf-8"))
        
        # README metadata file
        readme_txt = f"""BreachSense Inundation Model GIS Export
Dam Name: {simulation_data.get('dam_name')}
Breach Type: {simulation_data.get('breach_type')}
Breach Scale: {simulation_data.get('breach_size')}
Peak Discharge: {simulation_data.get('breach_params', {}).get('q_peak_cumec')} cumec
Coordinate System: WGS 84 (EPSG:4326)
Total Timesteps: {len(timesteps)}
"""
        zf.writestr("README_METADATA.txt", readme_txt.encode("utf-8"))
        
        # Attempt GeoPandas conversion if installed
        try:
            import geopandas as gpd
            import tempfile
            
            with tempfile.TemporaryDirectory() as tmpdir:
                gdf = gpd.GeoDataFrame.from_features(all_features, crs="EPSG:4326")
                shp_path = os.path.join(tmpdir, f"{dam_name}_inundation.shp")
                gdf.to_file(shp_path, driver="ESRI Shapefile")
                
                for ext in [".shp", ".shx", ".dbf", ".prj", ".cpg"]:
                    f_name = f"{dam_name}_inundation{ext}"
                    full_p = os.path.join(tmpdir, f_name)
                    if os.path.exists(full_p):
                        zf.write(full_p, arcname=f_name)
        except Exception as e:
            print(f"GeoPandas shapefile creation notice (using GeoJSON fallback package): {e}")

    buf.seek(0)
    return buf.getvalue()
